pipeline:
  name: Run Black Formatter
  identifier: run_black_formatter
  projectIdentifier: FlexApp2
  orgIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
    - stage:
        name: Format Check
        identifier: format_check
        type: CI
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Run Black
                  identifier: run_black
                  type: Run
                  spec:
                    shell: Sh
                    command: |
                      pip install black
                      black --check .
