[tool.black]
line-length = 140
target-version = ["py312"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 140
known_first_party = ["app", "tests"]
default_section = "THIRDPARTY"

[tool.pytest.ini_options]
markers = [
    "db: marks tests that require database access",
    "slow: marks tests that are slow",
    "unit: unit tests",
    "integration: integration tests",
    "functional: functional tests"
]